"""Model danych: encje, ograniczenia i indeksy.

Odpowiada sekcji 3.2 dokumentu koncepcyjnego oraz wymaganiom twardym
z sekcji 1.1 planu budowy: kwoty NUMERIC z jawnym netto/brutto i VAT,
daty biznesowe DATE, znaczniki techniczne TIMESTAMPTZ, miekkie usuwanie,
optimistic locking i log audytu tylko do zapisu.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "002_model_danych"
down_revision: str | None = "001_fundament"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Log audytu musi byc tylko do zapisu. Zapis w CLAUDE.md to konwencja, a konwencje
# sie lamie przy poprawianiu danych "na szybko". Wyzwalacz nie da sie zapomniec.
STRAZNIK_AUDYTU = """
CREATE OR REPLACE FUNCTION log_audytu_tylko_do_zapisu() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Log audytu jest tylko do zapisu. Operacja % jest zabroniona.', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_log_audytu_bez_zmian
    BEFORE UPDATE OR DELETE OR TRUNCATE ON log_audytu
    FOR EACH STATEMENT EXECUTE FUNCTION log_audytu_tylko_do_zapisu();
"""

USUN_STRAZNIKA_AUDYTU = """
DROP TRIGGER IF EXISTS trg_log_audytu_bez_zmian ON log_audytu;
DROP FUNCTION IF EXISTS log_audytu_tylko_do_zapisu();
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uzytkownik",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("imie_nazwisko", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("hash_hasla", sa.String(length=255), nullable=True),
        sa.Column(
            "rola",
            sa.Enum(
                "podglad",
                "operator",
                "zarzadca",
                "administrator",
                name="rolauzytkownika",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("aktywny", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "wymaga_zmiany_hasla", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("nieudane_logowania", sa.Integer(), server_default="0", nullable=False),
        sa.Column("zablokowany_do", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ostatnie_logowanie", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "budynek",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nazwa", sa.String(length=80), nullable=False),
        sa.Column("adres", sa.Text(), nullable=True),
        sa.Column("aktywny", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_budynek_usunieto_dnia"), "budynek", ["usunieto_dnia"], unique=False)
    op.create_index(
        "uq_budynek_nazwa_aktywny",
        "budynek",
        ["nazwa"],
        unique=True,
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.create_table(
        "log_audytu",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "kiedy", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "operacja",
            sa.Enum(
                "utworzenie",
                "zmiana",
                "usuniecie",
                "odczyt_wrazliwy",
                name="operacjaaudytu",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("tabela", sa.String(length=60), nullable=False),
        sa.Column("rekord_id", sa.BigInteger(), nullable=True),
        sa.Column("pole", sa.String(length=80), nullable=True),
        sa.Column("wartosc_stara", sa.Text(), nullable=True),
        sa.Column("wartosc_nowa", sa.Text(), nullable=True),
        sa.Column("id_zadania", sa.String(length=64), nullable=True),
        sa.Column("adres_ip", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(["uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audyt_kiedy", "log_audytu", ["kiedy"], unique=False)
    op.create_index("ix_audyt_rekord", "log_audytu", ["tabela", "rekord_id", "kiedy"], unique=False)
    op.create_index("ix_audyt_uzytkownik", "log_audytu", ["uzytkownik_id", "kiedy"], unique=False)
    op.create_table(
        "najemca",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nazwa_pelna", sa.String(length=300), nullable=False),
        sa.Column("nip", sa.String(length=10), nullable=True),
        sa.Column("regon", sa.String(length=14), nullable=True),
        sa.Column("krs", sa.String(length=10), nullable=True),
        sa.Column("adres_siedziby", sa.Text(), nullable=True),
        sa.Column("adres_korespondencyjny", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("telefon", sa.String(length=32), nullable=True),
        sa.Column("osoba_fizyczna", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notatki", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_najemca_nazwa_trgm",
        "najemca",
        ["nazwa_pelna"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"nazwa_pelna": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_najemca_usunieto_dnia"), "najemca", ["usunieto_dnia"], unique=False)
    op.create_index(
        "uq_najemca_nip_aktywny",
        "najemca",
        ["nip"],
        unique=True,
        postgresql_where=sa.text("nip IS NOT NULL AND usunieto_dnia IS NULL"),
    )
    op.create_table(
        "wskaznik_waloryzacji",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("rok", sa.Integer(), nullable=False),
        sa.Column(
            "rodzaj",
            sa.Enum(
                "gus_rok_do_roku",
                "gus_srednioroczny",
                "stala_stawka",
                name="rodzajwskaznika",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("wartosc_procent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("data_publikacji", sa.Date(), nullable=True),
        sa.Column("wprowadzil_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint("rok BETWEEN 2000 AND 2200", name="ck_wskaznik_rozsadny_rok"),
        sa.ForeignKeyConstraint(
            ["wprowadzil_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_wskaznik_rok_rodzaj", "wskaznik_waloryzacji", ["rok", "rodzaj"], unique=True
    )
    op.create_table(
        "lokal",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("budynek_id", sa.BigInteger(), nullable=False),
        sa.Column("oznaczenie", sa.String(length=60), nullable=False),
        sa.Column(
            "typ",
            sa.Enum(
                "handlowy",
                "biurowy",
                "magazyn",
                "miejsce_postojowe",
                "inny",
                name="typlokalu",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "wolny",
                "wynajety",
                "w_trakcie_wydania",
                name="statuslokalu",
                native_enum=False,
                length=48,
            ),
            server_default="wolny",
            nullable=False,
        ),
        sa.Column("kondygnacja", sa.String(length=30), nullable=True),
        sa.Column("powierzchnia_ewidencyjna", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["budynek_id"], ["budynek.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_lokal_budynek_status", "lokal", ["budynek_id", "status"], unique=False)
    op.create_index(op.f("ix_lokal_usunieto_dnia"), "lokal", ["usunieto_dnia"], unique=False)
    op.create_index(
        "uq_lokal_oznaczenie_w_budynku",
        "lokal",
        ["budynek_id", "oznaczenie"],
        unique=True,
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.create_table(
        "osoba_kontaktowa",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("najemca_id", sa.BigInteger(), nullable=False),
        sa.Column("imie_nazwisko", sa.String(length=160), nullable=False),
        sa.Column("stanowisko", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("telefon", sa.String(length=32), nullable=True),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["najemca_id"], ["najemca.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_osoba_kontaktowa_najemca_id"), "osoba_kontaktowa", ["najemca_id"], unique=False
    )
    op.create_index(
        op.f("ix_osoba_kontaktowa_usunieto_dnia"),
        "osoba_kontaktowa",
        ["usunieto_dnia"],
        unique=False,
    )
    op.create_table(
        "okres_najmu",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("lokal_id", sa.BigInteger(), nullable=False),
        sa.Column("najemca_id", sa.BigInteger(), nullable=False),
        sa.Column("data_zawarcia", sa.Date(), nullable=True),
        sa.Column("data_przekazania", sa.Date(), nullable=True),
        sa.Column(
            "bazuje_na_dacie",
            sa.Enum(
                "data_zawarcia",
                "data_przekazania",
                name="bazaokresunajmu",
                native_enum=False,
                length=48,
            ),
            server_default="data_przekazania",
            nullable=False,
        ),
        sa.Column("okres_zawarcia_miesiace", sa.Integer(), nullable=True),
        sa.Column("data_zakonczenia_planowana", sa.Date(), nullable=True),
        sa.Column("data_zakonczenia_faktyczna", sa.Date(), nullable=True),
        sa.Column("okres_wypowiedzenia_miesiace", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "przygotowanie",
                "aktywna",
                "wypowiedziana",
                "zakonczona",
                name="statusokresunajmu",
                native_enum=False,
                length=48,
            ),
            server_default="przygotowanie",
            nullable=False,
        ),
        sa.Column(
            "waloryzacja_podlega", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("waloryzacja_miesiac", sa.Integer(), nullable=True),
        sa.Column(
            "waloryzacja_rodzaj_wskaznika",
            sa.Enum(
                "gus_rok_do_roku",
                "gus_srednioroczny",
                "stala_stawka",
                name="rodzajwskaznika",
                native_enum=False,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("waloryzacja_stala_stawka", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("waloryzacja_pierwsza_data", sa.Date(), nullable=True),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "okres_zawarcia_miesiace IS NULL OR okres_zawarcia_miesiace > 0",
            name="ck_okres_najmu_dodatni_okres",
        ),
        sa.CheckConstraint(
            "waloryzacja_miesiac IS NULL OR waloryzacja_miesiac BETWEEN 1 AND 12",
            name="ck_okres_najmu_miesiac_waloryzacji",
        ),
        sa.ForeignKeyConstraint(["lokal_id"], ["lokal.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["najemca_id"], ["najemca.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_okres_najmu_koniec",
        "okres_najmu",
        ["data_zakonczenia_planowana", "status"],
        unique=False,
    )
    op.create_index(
        "ix_okres_najmu_lokal_status", "okres_najmu", ["lokal_id", "status"], unique=False
    )
    op.create_index("ix_okres_najmu_najemca", "okres_najmu", ["najemca_id"], unique=False)
    op.create_index(
        op.f("ix_okres_najmu_usunieto_dnia"), "okres_najmu", ["usunieto_dnia"], unique=False
    )
    op.create_index(
        "ix_okres_najmu_waloryzacja",
        "okres_najmu",
        ["waloryzacja_miesiac"],
        unique=False,
        postgresql_where=sa.text("waloryzacja_podlega AND usunieto_dnia IS NULL"),
    )
    op.create_table(
        "zdarzenie",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "typ",
            sa.Enum(
                "koniec_umowy_sie_zbliza",
                "minal_termin_wypowiedzenia",
                "umowa_wygasla_brak_nastepczej",
                "waloryzacja_sie_zbliza",
                "wskaznik_gus_opublikowany",
                "polisa_niedostarczona",
                "polisa_wygasa",
                "polisa_ponizej_kwoty",
                "kaucja_niewplacona",
                "kaucja_do_zwrotu",
                "weksel_do_przeliczenia",
                "przeglad_sie_zbliza",
                "przeglad_przeterminowany",
                "brak_protokolu_przekazania",
                "profil_niekompletny",
                "dokument_czeka_na_weryfikacje",
                "zadanie_wlasne",
                name="typzdarzenia",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("encja_typ", sa.String(length=40), nullable=False),
        sa.Column("encja_id", sa.BigInteger(), nullable=False),
        sa.Column("lokal_id", sa.BigInteger(), nullable=True),
        sa.Column("data_zdarzenia", sa.Date(), nullable=False),
        sa.Column(
            "waga",
            sa.Enum(
                "informacja",
                "ostrzezenie",
                "krytyczne",
                name="wagazdarzenia",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "otwarte",
                "obsluzone",
                "odroczone",
                name="statuszdarzenia",
                native_enum=False,
                length=48,
            ),
            server_default="otwarte",
            nullable=False,
        ),
        sa.Column("tresc", sa.String(length=500), nullable=False),
        sa.Column("przypisany_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("odroczone_do", sa.Date(), nullable=True),
        sa.Column("obsluzone_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("obsluzyl_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("notatka", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status <> 'odroczone' OR odroczone_do IS NOT NULL",
            name="ck_zdarzenie_odroczenie_ma_termin",
        ),
        sa.ForeignKeyConstraint(["lokal_id"], ["lokal.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["obsluzyl_uzytkownik_id"], ["uzytkownik.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["przypisany_uzytkownik_id"], ["uzytkownik.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_zdarzenie_lokal_status", "zdarzenie", ["lokal_id", "status"], unique=False)
    op.create_index(
        "ix_zdarzenie_otwarte",
        "zdarzenie",
        ["data_zdarzenia", "waga"],
        unique=False,
        postgresql_where=sa.text("status = 'otwarte' AND usunieto_dnia IS NULL"),
    )
    op.create_index(
        "ix_zdarzenie_przypisany", "zdarzenie", ["przypisany_uzytkownik_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_zdarzenie_usunieto_dnia"), "zdarzenie", ["usunieto_dnia"], unique=False
    )
    op.create_index(
        "uq_zdarzenie_klucz_naturalny",
        "zdarzenie",
        ["typ", "encja_typ", "encja_id", "data_zdarzenia"],
        unique=True,
    )
    op.create_table(
        "dokument",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("okres_najmu_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "typ",
            sa.Enum(
                "umowa",
                "aneks",
                "protokol_przekazania",
                "protokol_zdawczy",
                "polisa",
                "protokol_przegladu",
                "wypowiedzenie",
                "inne",
                name="typdokumentu",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("numer", sa.String(length=80), nullable=True),
        sa.Column("data_dokumentu", sa.Date(), nullable=True),
        sa.Column("data_obowiazywania_od", sa.Date(), nullable=True),
        sa.Column("plik_sciezka", sa.String(length=500), nullable=True),
        sa.Column("plik_nazwa_oryginalna", sa.String(length=300), nullable=True),
        sa.Column("hash_sha256", sa.String(length=64), nullable=True),
        sa.Column("rozmiar_bajty", sa.BigInteger(), nullable=True),
        sa.Column("typ_mime", sa.String(length=120), nullable=True),
        sa.Column("liczba_stron", sa.Integer(), nullable=True),
        sa.Column("dokument_nadrzedny_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status_przetworzenia",
            sa.Enum(
                "wgrany",
                "w_trakcie",
                "przetworzony",
                "blad",
                "pominiety",
                name="statusprzetworzenia",
                native_enum=False,
                length=48,
            ),
            server_default="wgrany",
            nullable=False,
        ),
        sa.Column("blad_przetwarzania", sa.Text(), nullable=True),
        sa.Column("wgral_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "dokument_nadrzedny_id IS NULL OR dokument_nadrzedny_id <> id",
            name="ck_dokument_nie_jest_wlasnym_rodzicem",
        ),
        sa.CheckConstraint(
            "hash_sha256 IS NULL OR char_length(hash_sha256) = 64", name="ck_dokument_dlugosc_hasha"
        ),
        sa.ForeignKeyConstraint(["dokument_nadrzedny_id"], ["dokument.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["okres_najmu_id"], ["okres_najmu.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["wgral_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dokument_do_weryfikacji",
        "dokument",
        ["status_przetworzenia"],
        unique=False,
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.create_index("ix_dokument_nadrzedny", "dokument", ["dokument_nadrzedny_id"], unique=False)
    op.create_index("ix_dokument_okres_typ", "dokument", ["okres_najmu_id", "typ"], unique=False)
    op.create_index(op.f("ix_dokument_usunieto_dnia"), "dokument", ["usunieto_dnia"], unique=False)
    op.create_index(
        "uq_dokument_hash",
        "dokument",
        ["hash_sha256"],
        unique=True,
        postgresql_where=sa.text("hash_sha256 IS NOT NULL AND usunieto_dnia IS NULL"),
    )
    op.create_table(
        "skladnik_oplaty",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("okres_najmu_id", sa.BigInteger(), nullable=False),
        sa.Column("nazwa", sa.String(length=120), nullable=False),
        sa.Column("klucz_parametru", sa.String(length=80), nullable=False),
        sa.Column("sposob_wyliczenia", sa.Text(), nullable=True),
        sa.Column("dzien_platnosci_miesiaca", sa.Integer(), nullable=True),
        sa.Column(
            "okres_rozliczeniowy",
            sa.Enum(
                "miesieczny",
                "kwartalny",
                "polroczny",
                "roczny",
                name="okresrozliczeniowy",
                native_enum=False,
                length=48,
            ),
            server_default="miesieczny",
            nullable=False,
        ),
        sa.Column(
            "czy_waloryzowany", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "dzien_platnosci_miesiaca IS NULL OR dzien_platnosci_miesiaca BETWEEN 1 AND 31",
            name="ck_skladnik_dzien_platnosci",
        ),
        sa.ForeignKeyConstraint(["okres_najmu_id"], ["okres_najmu.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_skladnik_dzien_platnosci", "skladnik_oplaty", ["dzien_platnosci_miesiaca"], unique=False
    )
    op.create_index(
        op.f("ix_skladnik_oplaty_usunieto_dnia"), "skladnik_oplaty", ["usunieto_dnia"], unique=False
    )
    op.create_index(
        "uq_skladnik_klucz_w_okresie",
        "skladnik_oplaty",
        ["okres_najmu_id", "klucz_parametru"],
        unique=True,
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.create_table(
        "obowiazek_przegladu",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("lokal_id", sa.BigInteger(), nullable=False),
        sa.Column("okres_najmu_id", sa.BigInteger(), nullable=True),
        sa.Column("element", sa.String(length=120), nullable=False),
        sa.Column(
            "kto_obciazany",
            sa.Enum("najemca", "wynajmujacy", name="ktoobciazany", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column("czestotliwosc_miesiace", sa.Integer(), nullable=True),
        sa.Column("ostatni_przeglad_data", sa.Date(), nullable=True),
        sa.Column("nastepny_przeglad_data", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "aktualny",
                "zbliza_sie",
                "przeterminowany",
                "nieustalony",
                name="statusprzegladu",
                native_enum=False,
                length=48,
            ),
            server_default="nieustalony",
            nullable=False,
        ),
        sa.Column("protokol_dokument_id", sa.BigInteger(), nullable=True),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "czestotliwosc_miesiace IS NULL OR czestotliwosc_miesiace > 0",
            name="ck_przeglad_dodatnia_czestotliwosc",
        ),
        sa.ForeignKeyConstraint(["lokal_id"], ["lokal.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["okres_najmu_id"], ["okres_najmu.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["protokol_dokument_id"], ["dokument.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_obowiazek_przegladu_usunieto_dnia"),
        "obowiazek_przegladu",
        ["usunieto_dnia"],
        unique=False,
    )
    op.create_index(
        "ix_przeglad_lokal_element", "obowiazek_przegladu", ["lokal_id", "element"], unique=False
    )
    op.create_index(
        "ix_przeglad_nastepny_termin",
        "obowiazek_przegladu",
        ["nastepny_przeglad_data"],
        unique=False,
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.create_table(
        "parametr_wartosc",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("okres_najmu_id", sa.BigInteger(), nullable=False),
        sa.Column("klucz", sa.String(length=80), nullable=False),
        sa.Column(
            "typ_wartosci",
            sa.Enum(
                "kwota",
                "liczba",
                "data",
                "flaga",
                "tekst",
                name="typwartosci",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("wartosc_kwota", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("wartosc_waluta", sa.String(length=3), nullable=True),
        sa.Column(
            "wartosc_rodzaj_kwoty",
            sa.Enum("netto", "brutto", name="rodzajkwoty", native_enum=False, length=48),
            nullable=True,
        ),
        sa.Column("wartosc_stawka_vat", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wartosc_liczba", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("wartosc_data", sa.Date(), nullable=True),
        sa.Column("wartosc_flaga", sa.Boolean(), nullable=True),
        sa.Column("wartosc_tekst", sa.Text(), nullable=True),
        sa.Column("obowiazuje_od", sa.Date(), nullable=False),
        sa.Column("obowiazuje_do", sa.Date(), nullable=True),
        sa.Column("dokument_zrodlowy_id", sa.BigInteger(), nullable=True),
        sa.Column("zrodlo_strona", sa.Integer(), nullable=True),
        sa.Column("zrodlo_paragraf", sa.String(length=80), nullable=True),
        sa.Column("zrodlo_offset_od", sa.Integer(), nullable=True),
        sa.Column("zrodlo_offset_do", sa.Integer(), nullable=True),
        sa.Column("pewnosc", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "status_weryfikacji",
            sa.Enum(
                "zaproponowana",
                "zatwierdzona",
                "poprawiona",
                "odrzucona",
                "niejednoznaczna",
                name="statusweryfikacji",
                native_enum=False,
                length=48,
            ),
            server_default="zaproponowana",
            nullable=False,
        ),
        sa.Column("zatwierdzil_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("zatwierdzono_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "\n            (typ_wartosci = 'kwota'  AND wartosc_kwota  IS NOT NULL\n                AND wartosc_liczba IS NULL AND wartosc_data IS NULL\n                AND wartosc_flaga IS NULL AND wartosc_tekst IS NULL)\n         OR (typ_wartosci = 'liczba' AND wartosc_liczba IS NOT NULL\n                AND wartosc_kwota IS NULL AND wartosc_data IS NULL\n                AND wartosc_flaga IS NULL AND wartosc_tekst IS NULL)\n         OR (typ_wartosci = 'data'   AND wartosc_data   IS NOT NULL\n                AND wartosc_kwota IS NULL AND wartosc_liczba IS NULL\n                AND wartosc_flaga IS NULL AND wartosc_tekst IS NULL)\n         OR (typ_wartosci = 'flaga'  AND wartosc_flaga  IS NOT NULL\n                AND wartosc_kwota IS NULL AND wartosc_liczba IS NULL\n                AND wartosc_data IS NULL AND wartosc_tekst IS NULL)\n         OR (typ_wartosci = 'tekst'  AND wartosc_tekst  IS NOT NULL\n                AND wartosc_kwota IS NULL AND wartosc_liczba IS NULL\n                AND wartosc_data IS NULL AND wartosc_flaga IS NULL)\n            ",
            name="ck_parametr_jedna_wartosc",
        ),
        sa.CheckConstraint(
            "typ_wartosci <> 'kwota' OR (wartosc_waluta IS NOT NULL AND wartosc_rodzaj_kwoty IS NOT NULL)",
            name="ck_parametr_kwota_pelna",
        ),
        sa.CheckConstraint(
            "wartosc_rodzaj_kwoty <> 'netto' OR wartosc_stawka_vat IS NOT NULL",
            name="ck_parametr_netto_ma_vat",
        ),
        sa.CheckConstraint(
            "(zatwierdzil_uzytkownik_id IS NULL) = (zatwierdzono_dnia IS NULL)",
            name="ck_parametr_slad_zatwierdzenia",
        ),
        sa.CheckConstraint(
            "obowiazuje_do IS NULL OR obowiazuje_do >= obowiazuje_od",
            name="ck_parametr_okres_niepusty",
        ),
        sa.CheckConstraint(
            "pewnosc IS NULL OR (pewnosc >= 0 AND pewnosc <= 1)", name="ck_parametr_pewnosc_zakres"
        ),
        sa.ForeignKeyConstraint(["dokument_zrodlowy_id"], ["dokument.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["okres_najmu_id"], ["okres_najmu.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["zatwierdzil_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_parametr_do_weryfikacji",
        "parametr_wartosc",
        ["dokument_zrodlowy_id", "status_weryfikacji"],
        unique=False,
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.create_index(
        "ix_parametr_stan_efektywny",
        "parametr_wartosc",
        ["okres_najmu_id", "klucz", sa.literal_column("obowiazuje_od DESC")],
        unique=False,
        postgresql_where=sa.text(
            "usunieto_dnia IS NULL AND status_weryfikacji IN ('zatwierdzona', 'poprawiona')"
        ),
    )
    op.create_index(
        op.f("ix_parametr_wartosc_usunieto_dnia"),
        "parametr_wartosc",
        ["usunieto_dnia"],
        unique=False,
    )
    op.create_table(
        "zabezpieczenie",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("okres_najmu_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "rodzaj",
            sa.Enum(
                "kaucja",
                "weksel",
                "gwarancja_bankowa",
                "polisa",
                name="rodzajzabezpieczenia",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "wymagane",
                "dostarczone",
                "zwrocone",
                "zatrzymane",
                "brak",
                name="statuszabezpieczenia",
                native_enum=False,
                length=48,
            ),
            server_default="wymagane",
            nullable=False,
        ),
        sa.Column("wymagana_wartosc", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("wymagana_waluta", sa.String(length=3), nullable=True),
        sa.Column(
            "wymagana_rodzaj_kwoty",
            sa.Enum("netto", "brutto", name="rodzajkwoty", native_enum=False, length=48),
            nullable=True,
        ),
        sa.Column("wymagana_stawka_vat", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("sposob_wyliczenia", sa.Text(), nullable=True),
        sa.Column("data_wymagalnosci", sa.Date(), nullable=True),
        sa.Column("data_dostarczenia", sa.Date(), nullable=True),
        sa.Column("data_waznosci", sa.Date(), nullable=True),
        sa.Column("data_zwrotu", sa.Date(), nullable=True),
        sa.Column("miejsce_przechowywania", sa.String(length=200), nullable=True),
        sa.Column("dokument_id", sa.BigInteger(), nullable=True),
        sa.Column("uwagi", sa.Text(), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usunieto_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usunal_uzytkownik_id", sa.BigInteger(), nullable=True),
        sa.Column("wersja", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "wymagana_wartosc IS NULL OR wymagana_rodzaj_kwoty <> 'netto' OR wymagana_stawka_vat IS NOT NULL",
            name="ck_zabezpieczenie_netto_ma_vat",
        ),
        sa.CheckConstraint(
            "wymagana_wartosc IS NULL OR (wymagana_waluta IS NOT NULL AND wymagana_rodzaj_kwoty IS NOT NULL)",
            name="ck_zabezpieczenie_kwota_pelna",
        ),
        sa.ForeignKeyConstraint(["dokument_id"], ["dokument.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["okres_najmu_id"], ["okres_najmu.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usunal_uzytkownik_id"], ["uzytkownik.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_zabezpieczenie_okres_rodzaj",
        "zabezpieczenie",
        ["okres_najmu_id", "rodzaj"],
        unique=False,
    )
    op.create_index(
        op.f("ix_zabezpieczenie_usunieto_dnia"), "zabezpieczenie", ["usunieto_dnia"], unique=False
    )
    op.create_index(
        "ix_zabezpieczenie_waznosc",
        "zabezpieczenie",
        ["data_waznosci"],
        unique=False,
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.create_index(
        "ix_zabezpieczenie_wymagalnosc",
        "zabezpieczenie",
        ["data_wymagalnosci"],
        unique=False,
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    # ### end Alembic commands ###

    op.execute(STRAZNIK_AUDYTU)


def downgrade() -> None:
    op.execute(USUN_STRAZNIKA_AUDYTU)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_zabezpieczenie_wymagalnosc",
        table_name="zabezpieczenie",
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.drop_index(
        "ix_zabezpieczenie_waznosc",
        table_name="zabezpieczenie",
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.drop_index(op.f("ix_zabezpieczenie_usunieto_dnia"), table_name="zabezpieczenie")
    op.drop_index("ix_zabezpieczenie_okres_rodzaj", table_name="zabezpieczenie")
    op.drop_table("zabezpieczenie")
    op.drop_index(op.f("ix_parametr_wartosc_usunieto_dnia"), table_name="parametr_wartosc")
    op.drop_index(
        "ix_parametr_stan_efektywny",
        table_name="parametr_wartosc",
        postgresql_where=sa.text(
            "usunieto_dnia IS NULL AND status_weryfikacji IN ('zatwierdzona', 'poprawiona')"
        ),
    )
    op.drop_index(
        "ix_parametr_do_weryfikacji",
        table_name="parametr_wartosc",
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.drop_table("parametr_wartosc")
    op.drop_index(
        "ix_przeglad_nastepny_termin",
        table_name="obowiazek_przegladu",
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.drop_index("ix_przeglad_lokal_element", table_name="obowiazek_przegladu")
    op.drop_index(op.f("ix_obowiazek_przegladu_usunieto_dnia"), table_name="obowiazek_przegladu")
    op.drop_table("obowiazek_przegladu")
    op.drop_index(
        "uq_skladnik_klucz_w_okresie",
        table_name="skladnik_oplaty",
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.drop_index(op.f("ix_skladnik_oplaty_usunieto_dnia"), table_name="skladnik_oplaty")
    op.drop_index("ix_skladnik_dzien_platnosci", table_name="skladnik_oplaty")
    op.drop_table("skladnik_oplaty")
    op.drop_index(
        "uq_dokument_hash",
        table_name="dokument",
        postgresql_where=sa.text("hash_sha256 IS NOT NULL AND usunieto_dnia IS NULL"),
    )
    op.drop_index(op.f("ix_dokument_usunieto_dnia"), table_name="dokument")
    op.drop_index("ix_dokument_okres_typ", table_name="dokument")
    op.drop_index("ix_dokument_nadrzedny", table_name="dokument")
    op.drop_index(
        "ix_dokument_do_weryfikacji",
        table_name="dokument",
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.drop_table("dokument")
    op.drop_index("uq_zdarzenie_klucz_naturalny", table_name="zdarzenie")
    op.drop_index(op.f("ix_zdarzenie_usunieto_dnia"), table_name="zdarzenie")
    op.drop_index("ix_zdarzenie_przypisany", table_name="zdarzenie")
    op.drop_index(
        "ix_zdarzenie_otwarte",
        table_name="zdarzenie",
        postgresql_where=sa.text("status = 'otwarte' AND usunieto_dnia IS NULL"),
    )
    op.drop_index("ix_zdarzenie_lokal_status", table_name="zdarzenie")
    op.drop_table("zdarzenie")
    op.drop_index(
        "ix_okres_najmu_waloryzacja",
        table_name="okres_najmu",
        postgresql_where=sa.text("waloryzacja_podlega AND usunieto_dnia IS NULL"),
    )
    op.drop_index(op.f("ix_okres_najmu_usunieto_dnia"), table_name="okres_najmu")
    op.drop_index("ix_okres_najmu_najemca", table_name="okres_najmu")
    op.drop_index("ix_okres_najmu_lokal_status", table_name="okres_najmu")
    op.drop_index("ix_okres_najmu_koniec", table_name="okres_najmu")
    op.drop_table("okres_najmu")
    op.drop_index(op.f("ix_osoba_kontaktowa_usunieto_dnia"), table_name="osoba_kontaktowa")
    op.drop_index(op.f("ix_osoba_kontaktowa_najemca_id"), table_name="osoba_kontaktowa")
    op.drop_table("osoba_kontaktowa")
    op.drop_index(
        "uq_lokal_oznaczenie_w_budynku",
        table_name="lokal",
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.drop_index(op.f("ix_lokal_usunieto_dnia"), table_name="lokal")
    op.drop_index("ix_lokal_budynek_status", table_name="lokal")
    op.drop_table("lokal")
    op.drop_index("uq_wskaznik_rok_rodzaj", table_name="wskaznik_waloryzacji")
    op.drop_table("wskaznik_waloryzacji")
    op.drop_index(
        "uq_najemca_nip_aktywny",
        table_name="najemca",
        postgresql_where=sa.text("nip IS NOT NULL AND usunieto_dnia IS NULL"),
    )
    op.drop_index(op.f("ix_najemca_usunieto_dnia"), table_name="najemca")
    op.drop_index(
        "ix_najemca_nazwa_trgm",
        table_name="najemca",
        postgresql_using="gin",
        postgresql_ops={"nazwa_pelna": "gin_trgm_ops"},
    )
    op.drop_table("najemca")
    op.drop_index("ix_audyt_uzytkownik", table_name="log_audytu")
    op.drop_index("ix_audyt_rekord", table_name="log_audytu")
    op.drop_index("ix_audyt_kiedy", table_name="log_audytu")
    op.drop_table("log_audytu")
    op.drop_index(
        "uq_budynek_nazwa_aktywny",
        table_name="budynek",
        postgresql_where=sa.text("usunieto_dnia IS NULL"),
    )
    op.drop_index(op.f("ix_budynek_usunieto_dnia"), table_name="budynek")
    op.drop_table("budynek")
    op.drop_table("uzytkownik")
    # ### end Alembic commands ###
