"""Sesje uzytkownikow.

Sesja zyje w bazie, a nie w samym ciasteczku: administrator musi moc uniewaznic
dostep natychmiast, a odczyty danych wrazliwych maja dac sie powiazac
z konkretnym logowaniem. W kolumnie token_hash lezy skrot, nigdy sam token.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "003_sesje"
down_revision: str | None = "002_model_danych"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sesja_uzytkownika",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uzytkownik_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("wygasa", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uniewazniona_dnia", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ostatnia_aktywnosc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("adres_ip", sa.String(length=45), nullable=True),
        sa.Column(
            "utworzono", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "zmodyfikowano",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["uzytkownik_id"], ["uzytkownik.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_sesja_uzytkownik", "sesja_uzytkownika", ["uzytkownik_id"], unique=False)
    op.create_index("ix_sesja_wygasa", "sesja_uzytkownika", ["wygasa"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sesja_wygasa", table_name="sesja_uzytkownika")
    op.drop_index("ix_sesja_uzytkownik", table_name="sesja_uzytkownika")
    op.drop_table("sesja_uzytkownika")
    # ### end Alembic commands ###
